version : '3'
services :
  php74-fpm:
     container_name: php74-fpm
     restart: always
     build: php-build
     volumes:
       - ./www:/var/www/html
     expose:
       - 9000

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx/
      - ./www:/var/www/html
    ports:
            - "443:443"

  mysql:
    container_name: mysql
    image: mariadb:10.3
    environment:
        MYSQL_ROOT_PASSWORD: rootdocker
    volumes:
        - ./db/:/var/lib/mysql
        - ./logs/mysql:/var/log/mysql
    ports:
      - 3306:3306
